version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
     - 80:80
   volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
     - app
   networks:
     - data-tier
     - app-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - data-tier

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - db
    networks:
      - app-tier

volumes:
  db-data:

networks:
  app-tier:
  data-tier: